Όταν προγραμματίζετε, τα σφάλματα συμβαίνουν. Είναι απλά μια πραγματικότητα της ζωής. Ίσως ο χρήστης έδωσε λάθος είσοδο. Ίσως ένας πόρος δικτύου δεν ήταν διαθέσιμος. Ίσως το πρόγραμμα εξαντλήθηκε από μνήμη. Ή ο προγραμματιστής μπορεί ακόμα και να έκανε λάθος!

Η λύση της Python για τα σφάλματα είναι οι εξαιρέσεις. Ίσως έχετε δει μια εξαίρεση πριν.

Oops! Ξεχάσατε να εκχωρήσετε τιμή στη μεταβλητή 'a'.

Αλλά μερικές φορές δεν θέλετε οι εξαιρέσεις να σταματήσουν εντελώς το πρόγραμμα. Ίσως θέλετε να κάνετε κάτι ειδικό όταν εμφανίζεται μια εξαίρεση. Αυτό γίνεται σε ένα μπλοκ *try/except*.

Να ένα απλό παράδειγμα: Υποθέστε ότι κάνετε επανάληψη πάνω από μια λίστα. Χρειάζεται να επαναλάβετε πάνω από 20 αριθμούς, αλλά η λίστα είναι φτιαγμένη από είσοδο χρήστη και ίσως να μην έχει 20 αριθμούς σε αυτήν. Αφού φτάσετε στο τέλος της λίστας, απλά θέλετε οι υπόλοιποι αριθμοί να ερμηνεύονται ως 0. Δείτε πώς μπορείτε να το κάνετε αυτό:

Εκεί, δεν ήταν πολύ δύσκολο! Μπορείτε να το κάνετε αυτό με οποιαδήποτε εξαίρεση. Για περισσότερες λεπτομέρειες σχετικά με τον χειρισμό εξαιρέσεων, μην ψάξετε περισσότερο από την [Python Docs](http://docs.python.org/tutorial/errors.html#handling-exceptions)

Άσκηση
--------

Χειριστείτε όλες τις εξαιρέσεις! Θυμηθείτε τα προηγούμενα μαθήματα για να επιστρέψετε το επώνυμο του ηθοποιού.