عند البرمجة، تحدث الأخطاء. إنها مجرد حقيقة في الحياة. قد يكون المستخدم أدخل بيانات خاطئة. ربما كان مورد الشبكة غير متاح. ربما نفد البرنامج من الذاكرة. أو ربما يكون المبرمج قد ارتكب خطأ!

الحل في بايثون للأخطاء هو الاستثناءات. ربما قد رأيت استثناءً من قبل.

    
Oops! نسيت تعيين قيمة للمتغير 'a'.

لكن في بعض الأحيان لا ترغب في أن توقف الاستثناءات البرنامج تمامًا. قد ترغب في القيام بشيء خاص عند حدوث استثناء. يتم ذلك في كتلة *try/except*.

إليك مثال بسيط: افترض أنك تتجول عبر قائمة. تحتاج إلى التجول عبر 20 رقمًا، ولكن القائمة مكونة من مدخلات المستخدم، وقد لا تحتوي على 20 رقمًا فيها. بعد أن تصل إلى نهاية القائمة، تود فقط أن يتم تفسير بقية الأرقام كـ 0. إليك كيفية القيام بذلك:

    

لم يكن ذلك صعبًا للغاية! يمكنك فعل ذلك مع أي استثناء. لمزيد من التفاصيل حول التعامل مع الاستثناءات، لا تنظر أبعد من 
[Python Docs](http://docs.python.org/tutorial/errors.html#handling-exceptions)

Exercise
--------

قم بمعالجة جميع الاستثناءات! تذكر الدروس السابقة لاسترجاع اسم العائلة للممثل.